name: Deploy Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Python Lambda
        uses: kylearector/py-lambda-action@master
        with:
          lambda_layer_arn: ${{ secrets.LAMBDA_LAYER_ARN }}
          lambda_function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
